apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nodereds.nodered.com
spec:
  group: nodered.com
  names:
    kind: NodeRed
    listKind: NodeRedList
    plural: nodereds
    singular: nodered
  additionalPrinterColumns:
    - name: Status
      type: string
      description: Node Red Deployment Status
      JSONPath: .status.phase
    - name: URL
      type: string
      description: Node Red URL
      JSONPath: .status.url
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
