# permissions for end users to view noderedrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderedrestore-viewer-role
rules:
- apiGroups:
  - nodered.com
  resources:
  - noderedrestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodered.com
  resources:
  - noderedrestores/status
  verbs:
  - get
