# permissions for end users to view nodereds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodered-viewer-role
rules:
- apiGroups:
  - nodered.com
  resources:
  - nodereds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodered.com
  resources:
  - nodereds/status
  verbs:
  - get
