# permissions for end users to edit noderedbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderedbackup-editor-role
rules:
- apiGroups:
  - nodered.com
  resources:
  - noderedbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodered.com
  resources:
  - noderedbackups/status
  verbs:
  - get
