# permissions for end users to view noderedbackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderedbackup-viewer-role
rules:
- apiGroups:
  - nodered.com
  resources:
  - noderedbackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodered.com
  resources:
  - noderedbackups/status
  verbs:
  - get
