# permissions for end users to edit noderedrestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: noderedrestore-editor-role
rules:
- apiGroups:
  - nodered.com
  resources:
  - noderedrestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodered.com
  resources:
  - noderedrestores/status
  verbs:
  - get
