# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/nodered.com_nodereds.yaml
- bases/nodered.com_noderedbackups.yaml
- bases/nodered.com_noderedrestores.yaml
# +kubebuilder:scaffold:crdkustomizeresource
