apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: node-red-ansible-operator
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-operator
  labels:
    control-plane: node-red-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: node-red-ansible-operator
  template:
    metadata:
      labels:
        control-plane: node-red-ansible-operator
    spec:
      serviceAccountName: node-red-operator
      containers:
        - name: manager
          # Replace this with the built image name
          image: "registry.connect.redhat.com/ibm-edge/node-red-operator:v-0.0.3"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "node-red-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: RELATED_IMAGE_NODERED
              value: registry.connect.redhat.com/ibm-edge/node-red:v0.0.3
            - name: RELATED_IMAGE_NODERED_BACKUP
              value: registry.connect.redhat.com/ibm-edge/node-red-backup-restore:v0.0.1
            - name: RELATED_IMAGE_NODERED_RESTORE
              value: registry.connect.redhat.com/ibm-edge/node-red-backup-restore:v0.0.1
      volumes:
        - name: runner
          emptyDir: {}

